apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-db-config
data:
  DATABASE_NAME: "{{ .Values.postgres.database }}"
  DATABASE_HOST: "{{ .Values.postgres.service }}.{{ .Values.postgres.namespace}}"
  DATABASE_USERNAME: "{{ .Values.postgres.user }}"
