{{- range .Values.crons }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ .command }}
spec:
  schedule: {{ .schedule | quote }}
  timeZone: "Europe/Berlin"
  suspend: {{ default false .suspend }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 1200
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          initContainers:
            - name: flyway
              image: {{ $.Values.image.migrations }}:{{ $.Values.appVersion }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ ALL ]
              envFrom:
                - secretRef:
                    name: {{ $.Release.Name }}-db
              env:
                - name: FLYWAY_URL
                  value: jdbc:postgresql://$(DATABASE_HOST):5432/$(DATABASE_NAME)
                - name: FLYWAY_USER
                  value: $(DATABASE_USERNAME)
                - name: FLYWAY_PASSWORD
                  value: $(DATABASE_PASSWORD)
          containers:
            - name: app
              image: {{ $.Values.image.app }}:{{ $.Values.appVersion }}
              args:
                - {{ .command }}
              resources:
                limits:
                  cpu: 1000m
                requests:
                  cpu: 1000m
                  memory: 128Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ ALL ]
              envFrom:
                - configMapRef:
                    name: {{ $.Release.Name }}-base
                - secretRef:
                    name: {{ $.Release.Name }}-db
                - secretRef:
                    name: {{ $.Release.Name }}-secrets
{{- end }}
