---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  replicas: 1
  revisionHistoryLimit: 1
  serviceName: {{ .Release.Name }}-update-handler
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      initContainers:
        - name: flyway
          image: {{ .Values.image.migrations }}:{{ .Values.appVersion }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-db-config
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DATABASE_HOST):5432/$(DATABASE_NAME)
            - name: FLYWAY_USER
              value: $(DATABASE_USERNAME)
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.user }}.{{ .Values.postgres.service }}.credentials.postgresql.acid.zalan.do
                  key: password
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          args:
            - handle-updates
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 10m
              memory: 128Mi
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.user }}.{{ .Values.postgres.service }}.credentials.postgresql.acid.zalan.do
                  key: password
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-telegram
            - configMapRef:
                name: {{ .Release.Name }}-gcp
            - configMapRef:
                name: {{ .Release.Name }}-db-config
            - secretRef:
                name: {{ .Release.Name }}-secrets

