---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  replicas: 0
  revisionHistoryLimit: 1
  serviceName: {{ .Release.Name }}-update-handler
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      initContainers:
        - name: flyway
          image: {{ .Values.image.migrations }}:{{ .Values.appVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-db
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DATABASE_HOST):5432/$(DATABASE_NAME)
            - name: FLYWAY_USER
              value: $(DATABASE_USERNAME)
            - name: FLYWAY_PASSWORD
              value: $(DATABASE_PASSWORD)
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          args:
            - handle-updates
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.user }}.{{ .Values.postgres.service }}.credentials.postgresql.acid.zalan.do
                  key: password
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-base
            - secretRef:
                name: {{ .Release.Name }}-db
            - secretRef:
                name: {{ .Release.Name }}-secrets

