---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      initContainers:
        - name: flyway
          image: {{ .Values.image.migrations }}:{{ .Values.appVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DATABASE__HOST):5432/$(DATABASE__NAME)
            - name: FLYWAY_USER
              value: $(DATABASE__USERNAME)
            - name: FLYWAY_PASSWORD
              value: $(DATABASE__PASSWORD)
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          args:
            - handle-updates
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-base
            - secretRef:
                name: {{ .Release.Name }}-db
            - secretRef:
                name: {{ .Release.Name }}-secrets
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: {{ .Release.Name }}-update-handler
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats-headless.nats-system.svc.cluster.local:8222"
        account: "$G"
        stream: "telegram-updates"
        consumer: "mood"
